name: Deploy Svelte App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun i

    - name: Build project
      run: bun run build

    - name: Deploy to GitHub Pages
      run: NODE_ENV=production bun run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
